/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as myNftFactorySol from "./MyNFTFactory.sol";
export type { myNftFactorySol };
export type { Employees } from "./Employees";
export type { MyNFT } from "./MyNFT";
export type { MyNFTToken } from "./MyNFTToken";
export * as factories from "./factories";
export { Employees__factory } from "./factories/Employees__factory";
export { MyNFT__factory } from "./factories/MyNFT__factory";
export type { MyNFTTokenFactory } from "./MyNFTFactory.sol/MyNFTTokenFactory";
export { MyNFTTokenFactory__factory } from "./factories/MyNFTFactory.sol/MyNFTTokenFactory__factory";
export { MyNFTToken__factory } from "./factories/MyNFTToken__factory";
