/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as myNftFactorySol from "./MyNFTFactory.sol";
export { Employees__factory } from "./Employees__factory";
export { MyNFT__factory } from "./MyNFT__factory";
export { MyNFTToken__factory } from "./MyNFTToken__factory";
